sudo: false
dist: trusty
language: node_js
node_js:
  - 8
cache:
  directories:
  - node_modules
script:
  - yarn run test
  - yarn run build
branches:
  only:
  - master
deploy:
  - provider: pages
    email: terrance@harvestprofit.com
    github_token: $GITHUB_TOKEN
    local_dir: build
    name: Terrance
    on:
      branch: master
    skip_cleanup: true
